/**
 * Coming back after a reboot.
 *
 * The agent handles every shutdown it gets to observe. A power cut is not one
 * of those, and nothing inside a process can restart that process. So the
 * honest answer is a service unit: the thing the operating system already has
 * for "start this at boot and keep it running".
 *
 * Generated rather than hand-written because the details that matter are the
 * ones people leave out — restarting on failure, a delay so a flapping agent
 * does not spin, and `--resume` so a machine with nobody at the keyboard can
 * still authenticate.
 */

export type ServiceKind = "systemd" | "launchd";

export interface ServiceOptions {
  /** How to invoke umwelten on this machine. */
  command: string;
  /** Where the agent's configuration and credential live. */
  supplierDir: string;
  user?: string;
  label?: string;
}

export function defaultServiceKind(platform: NodeJS.Platform): ServiceKind | undefined {
  if (platform === "linux") return "systemd";
  if (platform === "darwin") return "launchd";
  return undefined;
}

export function systemdUnit(opts: ServiceOptions): string {
  const label = opts.label ?? "umwelten-supplier";
  return `# ${label}.service — generated by umwelten
#
#   sudo cp ${label}.service /etc/systemd/system/
#   sudo systemctl enable --now ${label}
#
# Run \`umwelten supplier serve\` once by hand first: this unit resumes a saved
# configuration and will not start without one.

[Unit]
Description=umwelten supplier agent
# The agent talks to the Exchange over the network, and to a runtime that may
# pull weights. Starting before the network is up costs a failed start and a
# restart delay.
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
${opts.user ? `User=${opts.user}\n` : ""}Environment=UMWELTEN_SUPPLIER_DIR=${opts.supplierDir}
ExecStart=${opts.command} supplier serve --resume
# The agent withdraws its Offers on SIGTERM, so give it room to tell the
# Exchange before the machine goes down. A supplier that vanishes leaves the
# Exchange routing into nothing until the Offers expire.
KillSignal=SIGTERM
TimeoutStopSec=30
Restart=always
# Long enough that a genuinely broken agent does not spin, short enough that a
# transient failure costs minutes rather than an afternoon.
RestartSec=30

[Install]
WantedBy=multi-user.target
`;
}

export function launchdPlist(opts: ServiceOptions): string {
  const label = opts.label ?? "ai.thefocus.umwelten.supplier";
  const [program, ...args] = opts.command.split(" ");
  const programArgs = [program, ...args, "supplier", "serve", "--resume"]
    .map((a) => `    <string>${a}</string>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${label}.plist — generated by umwelten

       cp ${label}.plist ~/Library/LaunchAgents/
       launchctl load -w ~/Library/LaunchAgents/${label}.plist

     Run \`umwelten supplier serve\` once by hand first: this resumes a saved
     configuration and will not start without one. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
${programArgs}
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>UMWELTEN_SUPPLIER_DIR</key>
    <string>${opts.supplierDir}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <!-- Long enough that a genuinely broken agent does not spin. -->
  <key>ThrottleInterval</key>
  <integer>30</integer>
  <!-- The agent withdraws its Offers on SIGTERM; give it room to say so. -->
  <key>ExitTimeOut</key>
  <integer>30</integer>
</dict>
</plist>
`;
}

export function renderService(kind: ServiceKind, opts: ServiceOptions): string {
  return kind === "systemd" ? systemdUnit(opts) : launchdPlist(opts);
}
